/**
 * Curated catalogue of motion types.
 *
 * This list backs the `MotionType: Choice` XETO spec (see Agent B's spec build)
 * and the combo dropdown used to tag motions in the UI. Entries are sourced
 * from:
 *   - `user-data`  — observed in this user's filings (Texas family law +
 *                    appellate practice)
 *   - `texas-rules` — Texas Rules of Civil Procedure / Appellate Procedure
 *   - `frcp`        — Federal Rules of Civil Procedure
 *   - `practice`    — common civil-litigation motions not yet observed in the
 *                     user's data but expected to come up
 *
 * Keep this file plain data — no logic. Sorted alphabetically by displayName
 * (en-US locale-compare).
 */

export type MotionTypeCategory =
  | 'disposition'
  | 'discovery'
  | 'scheduling'
  | 'procedural'
  | 'appellate'
  | 'family-law'
  | 'evidence'
  | 'protective'
  | 'other';

export interface MotionTypeEntry {
  /** camelCase identifier — used as XETO Choice marker name. */
  slug: string;
  /** Human-readable label shown in the combo dropdown. */
  displayName: string;
  category: MotionTypeCategory;
  /** One-line description for tooltips / docs. */
  shortDoc: string;
  source: 'user-data' | 'texas-rules' | 'frcp' | 'practice';
  /** Alternative search terms — combo UI filters displayName AND aliases. */
  aliases?: string[];
}

export const MOTION_TYPES: readonly MotionTypeEntry[] = [
  {
    slug: 'antiSuitInjunction',
    displayName: 'Motion for Anti-Suit Injunction',
    category: 'protective',
    shortDoc: 'Asks the court to enjoin a party from prosecuting a parallel suit elsewhere.',
    source: 'practice',
  },
  {
    slug: 'attorneyFees',
    displayName: 'Motion for Attorney’s Fees',
    category: 'procedural',
    shortDoc: 'Asks the court to award attorney’s fees to the prevailing or moving party.',
    source: 'practice',
    aliases: ['Fees', 'Fee Application'],
  },
  {
    slug: 'forBillOfReview',
    displayName: 'Motion for Bill of Review',
    category: 'family-law',
    shortDoc: 'Equitable Texas action to vacate a prior judgment after appellate timetables have run.',
    source: 'user-data',
    aliases: ['Bill of Review', 'BOR'],
  },
  {
    slug: 'bondReduction',
    displayName: 'Motion for Bond Reduction',
    category: 'other',
    shortDoc: 'Asks a criminal court to lower the amount of bail required for pretrial release.',
    source: 'practice',
    aliases: ['Reduce Bail', 'Bail Reduction'],
  },
  {
    slug: 'cashCollateral',
    displayName: 'Motion for Cash Collateral',
    category: 'other',
    shortDoc: 'Bankruptcy debtor asks the court for permission to use cash collateral securing a creditor.',
    source: 'practice',
    aliases: ['Cash Collateral Use'],
  },
  {
    slug: 'clarification',
    displayName: 'Motion for Clarification',
    category: 'procedural',
    shortDoc: 'Asks the court to clarify an ambiguous ruling or order before entry.',
    source: 'user-data',
  },
  {
    slug: 'classCertification',
    displayName: 'Motion for Class Certification',
    category: 'procedural',
    shortDoc: 'Asks the court to certify the case to proceed as a class action under Rule 23.',
    source: 'frcp',
    aliases: ['Rule 23', 'Certify Class'],
  },
  {
    slug: 'contemptSupport',
    displayName: 'Motion for Contempt (Failure to Pay Support)',
    category: 'family-law',
    shortDoc: 'Asks the court to hold an obligor in contempt for failing to pay child or spousal support.',
    source: 'user-data',
    aliases: ['Enforce Support', 'Contempt Support'],
  },
  {
    slug: 'contemptVisitation',
    displayName: 'Motion for Contempt (Visitation Interference)',
    category: 'family-law',
    shortDoc: 'Asks the court to hold a party in contempt for denying or interfering with court-ordered possession.',
    source: 'user-data',
    aliases: ['Contempt Visitation', 'Possession Interference'],
  },
  {
    slug: 'continue',
    displayName: 'Motion for Continuance',
    category: 'scheduling',
    shortDoc: 'Asks the court to postpone a hearing, trial, or deadline.',
    source: 'user-data',
    aliases: ['Continuance', 'Postpone'],
  },
  {
    slug: 'defaultJudgment',
    displayName: 'Motion for Default Judgment',
    category: 'disposition',
    shortDoc: 'Asks the court to enter judgment against a party who failed to answer or appear.',
    source: 'practice',
  },
  {
    slug: 'directedVerdict',
    displayName: 'Motion for Directed Verdict',
    category: 'disposition',
    shortDoc: 'Asks the court to rule for the movant at trial because no reasonable jury could find otherwise.',
    source: 'practice',
    aliases: ['Directed Verdict', 'DV'],
  },
  {
    slug: 'enBancReconsideration',
    displayName: 'Motion for En Banc Reconsideration',
    category: 'appellate',
    shortDoc: 'Asks the full appellate court (not just a panel) to rehear the case.',
    source: 'texas-rules',
    aliases: ['En Banc'],
  },
  {
    slug: 'enforce',
    displayName: 'Motion for Enforcement',
    category: 'family-law',
    shortDoc: 'Asks the court to enforce a prior order (typically a family-law decree).',
    source: 'practice',
    aliases: ['Enforcement', 'Contempt'],
  },
  {
    slug: 'expediteScheduling',
    displayName: 'Motion for Expedited Scheduling Order',
    category: 'scheduling',
    shortDoc: 'Asks the court to issue an expedited scheduling order for emergency relief.',
    source: 'user-data',
    aliases: ['Expedite'],
  },
  {
    slug: 'extensionOfTime',
    displayName: 'Motion for Extension of Time',
    category: 'scheduling',
    shortDoc: 'Asks the court to extend a deadline (commonly briefing deadlines).',
    source: 'user-data',
    aliases: ['Extension'],
  },
  {
    slug: 'inCameraReview',
    displayName: 'Motion for In Camera Review',
    category: 'discovery',
    shortDoc: 'Asks the judge to privately inspect documents before ruling on privilege.',
    source: 'practice',
  },
  {
    slug: 'judgmentNotwithstandingVerdict',
    displayName: 'Motion for Judgment Notwithstanding the Verdict',
    category: 'disposition',
    shortDoc: 'Asks the court to override the jury’s verdict because it lacks legal support.',
    source: 'practice',
    aliases: ['JNOV', 'Renewed JMOL', 'Rule 50(b)'],
  },
  {
    slug: 'judgmentOnPleadings',
    displayName: 'Motion for Judgment on the Pleadings',
    category: 'disposition',
    shortDoc: 'Asks the court to enter judgment based only on the pleadings under Rule 12(c).',
    source: 'frcp',
    aliases: ['12(c)', 'JOP'],
  },
  {
    slug: 'leaveToAmend',
    displayName: 'Motion for Leave to Amend',
    category: 'procedural',
    shortDoc: 'Asks the court for permission to amend a pleading after the deadline.',
    source: 'practice',
    aliases: ['Amend Pleadings', 'Leave to Amend'],
  },
  {
    slug: 'leaveToFile',
    displayName: 'Motion for Leave to File',
    category: 'procedural',
    shortDoc: 'Asks the court for permission to file a pleading out of time or beyond page limits.',
    source: 'user-data',
    aliases: ['Leave'],
  },
  {
    slug: 'leaveToFileAmicus',
    displayName: 'Motion for Leave to File Amicus Brief',
    category: 'appellate',
    shortDoc: 'Asks an appellate court for permission to file a friend-of-the-court brief.',
    source: 'practice',
    aliases: ['Amicus', 'Amicus Curiae'],
  },
  {
    slug: 'mediation',
    displayName: 'Motion for Mediation',
    category: 'procedural',
    shortDoc: 'Asks the court to order the parties to mediation.',
    source: 'user-data',
  },
  {
    slug: 'mentalExamination',
    displayName: 'Motion for Mental or Physical Examination',
    category: 'discovery',
    shortDoc: 'Asks the court to order a party to submit to a Rule 35 mental or physical exam.',
    source: 'frcp',
    aliases: ['Rule 35', 'IME'],
  },
  {
    slug: 'mistrial',
    displayName: 'Motion for Mistrial',
    category: 'procedural',
    shortDoc: 'Asks the court to declare a mistrial due to prejudicial error during proceedings.',
    source: 'practice',
    aliases: ['Mistrial'],
  },
  {
    slug: 'nameChange',
    displayName: 'Motion for Name Change',
    category: 'family-law',
    shortDoc: 'Asks the court to formally change the legal name of an adult or child.',
    source: 'practice',
    aliases: ['Change of Name'],
  },
  {
    slug: 'newTrial',
    displayName: 'Motion for New Trial',
    category: 'procedural',
    shortDoc: 'Asks the trial court to set aside the judgment and grant a new trial.',
    source: 'user-data',
    aliases: ['MNT'],
  },
  {
    slug: 'oralArgument',
    displayName: 'Motion for Oral Argument',
    category: 'appellate',
    shortDoc: 'Asks an appellate court to set the case for oral argument.',
    source: 'practice',
  },
  {
    slug: 'partialSummaryJudgment',
    displayName: 'Motion for Partial Summary Judgment',
    category: 'disposition',
    shortDoc: 'Asks the court to resolve some — but not all — claims as a matter of law.',
    source: 'practice',
    aliases: ['PSJ', 'MPSJ'],
  },
  {
    slug: 'permanentInjunction',
    displayName: 'Motion for Permanent Injunction',
    category: 'protective',
    shortDoc: 'Asks the court for a final order permanently barring specified conduct.',
    source: 'practice',
  },
  {
    slug: 'preliminaryInjunction',
    displayName: 'Motion for Preliminary Injunction',
    category: 'protective',
    shortDoc: 'Asks the court for an injunction maintaining the status quo through trial.',
    source: 'frcp',
    aliases: ['PI', 'Rule 65'],
  },
  {
    slug: 'protectiveOrder',
    displayName: 'Motion for Protective Order',
    category: 'discovery',
    shortDoc: 'Asks the court to limit or shield discovery to prevent harm or harassment.',
    source: 'practice',
  },
  {
    slug: 'qdroApproval',
    displayName: 'Motion for QDRO Approval',
    category: 'family-law',
    shortDoc: 'Asks the court to sign a Qualified Domestic Relations Order dividing retirement benefits.',
    source: 'practice',
    aliases: ['QDRO'],
  },
  {
    slug: 'reconsider',
    displayName: 'Motion for Reconsideration',
    category: 'procedural',
    shortDoc: 'Asks the court to reconsider a prior ruling, often based on new evidence.',
    source: 'user-data',
    aliases: ['Reconsider', 'MFR'],
  },
  {
    slug: 'reduceArrearsToJudgment',
    displayName: 'Motion for Reduction of Arrears to Judgment',
    category: 'family-law',
    shortDoc: 'Asks the court to reduce unpaid child or spousal support to an enforceable money judgment.',
    source: 'practice',
    aliases: ['Arrears Judgment'],
  },
  {
    slug: 'rehearing',
    displayName: 'Motion for Rehearing',
    category: 'appellate',
    shortDoc: 'Asks an appellate panel to rehear the case after a decision.',
    source: 'texas-rules',
  },
  {
    slug: 'reliefFromStay',
    displayName: 'Motion for Relief from Automatic Stay',
    category: 'other',
    shortDoc: 'Bankruptcy creditor asks the court to lift the automatic stay so it can pursue collateral.',
    source: 'practice',
    aliases: ['Lift Stay', '362 Relief'],
  },
  {
    slug: 'remoteAppearance',
    displayName: 'Motion for Remote Appearance',
    category: 'procedural',
    shortDoc: 'Asks the court for permission to appear by video or telephone.',
    source: 'user-data',
    aliases: ['Remote Hearing', 'Zoom Appearance'],
  },
  {
    slug: 'sanctions',
    displayName: 'Motion for Sanctions',
    category: 'discovery',
    shortDoc: 'Asks the court to penalize a party for discovery abuse or frivolous conduct.',
    source: 'user-data',
    aliases: ['Sanctions', 'Rule 11'],
  },
  {
    slug: 'spoliationSanctions',
    displayName: 'Motion for Sanctions (Spoliation of Evidence)',
    category: 'discovery',
    shortDoc: 'Asks the court to sanction a party for destroying or failing to preserve evidence.',
    source: 'practice',
    aliases: ['Spoliation'],
  },
  {
    slug: 'setChildSupport',
    displayName: 'Motion for Set Child Support',
    category: 'family-law',
    shortDoc: 'Asks the court to set an initial child-support obligation under the Texas guidelines.',
    source: 'practice',
    aliases: ['Set Support'],
  },
  {
    slug: 'sever',
    displayName: 'Motion for Severance',
    category: 'procedural',
    shortDoc: 'Asks the court to split claims or parties into separate actions.',
    source: 'practice',
    aliases: ['Sever'],
  },
  {
    slug: 'speedyTrial',
    displayName: 'Motion for Speedy Trial',
    category: 'other',
    shortDoc: 'Asks a criminal court to enforce the defendant’s right to a prompt trial.',
    source: 'practice',
  },
  {
    slug: 'standardPossessionOrder',
    displayName: 'Motion for Standard Possession Order',
    category: 'family-law',
    shortDoc: 'Asks the court to enter the Texas Standard Possession Order for periods of possession.',
    source: 'practice',
    aliases: ['SPO'],
  },
  {
    slug: 'stayOfRemoval',
    displayName: 'Motion for Stay of Removal',
    category: 'other',
    shortDoc: 'Asks an immigration court or BIA to stay the noncitizen’s removal pending review.',
    source: 'practice',
  },
  {
    slug: 'stayPendingAppeal',
    displayName: 'Motion for Stay Pending Appeal',
    category: 'appellate',
    shortDoc: 'Asks the court to suspend enforcement of the judgment while the appeal is pending.',
    source: 'user-data',
    aliases: ['Stay', 'Emergency Stay'],
  },
  {
    slug: 'substitutedService',
    displayName: 'Motion for Substituted Service',
    category: 'procedural',
    shortDoc: 'Asks the court for permission to serve a party by alternative means.',
    source: 'user-data',
  },
  {
    slug: 'substituteCounselOnAppeal',
    displayName: 'Motion for Substitution of Counsel on Appeal',
    category: 'appellate',
    shortDoc: 'Notifies an appellate court that appellate counsel is changing.',
    source: 'practice',
  },
  {
    slug: 'summaryJudgment',
    displayName: 'Motion for Summary Judgment',
    category: 'disposition',
    shortDoc: 'Asks the court to rule for the movant as a matter of law without trial.',
    source: 'practice',
    aliases: ['MSJ', 'Summary Judgment'],
  },
  {
    slug: 'temporaryOrders',
    displayName: 'Motion for Temporary Orders',
    category: 'family-law',
    shortDoc: 'Asks the court for interim orders (support, custody, possession) pending final hearing.',
    source: 'user-data',
    aliases: ['Temp Orders', 'TO'],
  },
  {
    slug: 'temporaryRestrainingOrder',
    displayName: 'Motion for Temporary Restraining Order',
    category: 'protective',
    shortDoc: 'Asks the court for an immediate, short-term order barring specified conduct.',
    source: 'user-data',
    aliases: ['TRO'],
  },
  {
    slug: 'withholdingOrder',
    displayName: 'Motion for Withholding Order',
    category: 'family-law',
    shortDoc: 'Asks the court to issue an income-withholding order for child or spousal support.',
    source: 'practice',
    aliases: ['Income Withholding', 'IWO'],
  },
  {
    slug: 'inLimine',
    displayName: 'Motion in Limine',
    category: 'evidence',
    shortDoc: 'Asks the court to bar mention of specified evidence before trial begins.',
    source: 'practice',
    aliases: ['MIL', 'Limine'],
  },
  {
    slug: 'abate',
    displayName: 'Motion to Abate',
    category: 'appellate',
    shortDoc: 'Asks the court to pause or suspend proceedings, often pending another action.',
    source: 'user-data',
    aliases: ['Abatement'],
  },
  {
    slug: 'abateAndConsolidate',
    displayName: 'Motion to Abate and Consolidate',
    category: 'appellate',
    shortDoc: 'Combined request to pause proceedings and merge related appeals into one.',
    source: 'user-data',
  },
  {
    slug: 'abateAndRemand',
    displayName: 'Motion to Abate and Remand',
    category: 'appellate',
    shortDoc: 'Asks the appellate court to suspend the appeal and send the case back to the trial court.',
    source: 'user-data',
  },
  {
    slug: 'amendPleadings',
    displayName: 'Motion to Amend Pleadings',
    category: 'procedural',
    shortDoc: 'Asks the court to allow amendment of a complaint, answer, or other pleading.',
    source: 'practice',
    aliases: ['Amend'],
  },
  {
    slug: 'appointReceiver',
    displayName: 'Motion to Appoint Receiver',
    category: 'family-law',
    shortDoc: 'Asks the court to appoint a neutral third party to take custody of assets or a business.',
    source: 'user-data',
    aliases: ['Receiver', 'Post-Judgment Receiver'],
  },
  {
    slug: 'bifurcate',
    displayName: 'Motion to Bifurcate',
    category: 'procedural',
    shortDoc: 'Asks the court to split trial into separate phases (e.g., liability and damages).',
    source: 'practice',
    aliases: ['Bifurcation'],
  },
  {
    slug: 'compelArbitration',
    displayName: 'Motion to Compel Arbitration',
    category: 'procedural',
    shortDoc: 'Asks the court to send the dispute to arbitration under a binding agreement.',
    source: 'practice',
    aliases: ['Arbitration', 'FAA'],
  },
  {
    slug: 'compelDeposition',
    displayName: 'Motion to Compel Deposition',
    category: 'discovery',
    shortDoc: 'Asks the court to order a witness or party to appear for deposition.',
    source: 'practice',
    aliases: ['Compel Depo'],
  },
  {
    slug: 'compelDiscovery',
    displayName: 'Motion to Compel Discovery',
    category: 'discovery',
    shortDoc: 'Asks the court to force a party to respond to discovery requests.',
    source: 'user-data',
    aliases: ['MTC', 'Compel'],
  },
  {
    slug: 'compelInterrogatories',
    displayName: 'Motion to Compel Interrogatory Answers',
    category: 'discovery',
    shortDoc: 'Asks the court to order full answers to written interrogatories.',
    source: 'practice',
    aliases: ['Compel Rogs', 'Rogs'],
  },
  {
    slug: 'compelProduction',
    displayName: 'Motion to Compel Production of Documents',
    category: 'discovery',
    shortDoc: 'Asks the court to order production of documents under Rule 34.',
    source: 'practice',
    aliases: ['Compel RFP', 'RFP'],
  },
  {
    slug: 'consolidate',
    displayName: 'Motion to Consolidate',
    category: 'appellate',
    shortDoc: 'Asks the court to merge two or more related cases or appeals.',
    source: 'user-data',
    aliases: ['Consolidation'],
  },
  {
    slug: 'convertBankruptcy',
    displayName: 'Motion to Convert (Bankruptcy)',
    category: 'other',
    shortDoc: 'Asks the bankruptcy court to convert a case between chapters (e.g., Chapter 7 to 13).',
    source: 'practice',
    aliases: ['Convert Case'],
  },
  {
    slug: 'decertifyClass',
    displayName: 'Motion to Decertify Class',
    category: 'procedural',
    shortDoc: 'Asks the court to reverse a prior class-certification ruling.',
    source: 'practice',
    aliases: ['Decertify'],
  },
  {
    slug: 'dismiss',
    displayName: 'Motion to Dismiss',
    category: 'disposition',
    shortDoc: 'Asks the court to throw the case out, typically for failure to state a claim.',
    source: 'user-data',
    aliases: ['MTD', '12(b)(6)'],
  },
  {
    slug: 'dismissBankruptcy',
    displayName: 'Motion to Dismiss (Bankruptcy)',
    category: 'other',
    shortDoc: 'Asks the bankruptcy court to dismiss the case for cause, abuse, or failure to comply.',
    source: 'practice',
  },
  {
    slug: 'dismissAppeal',
    displayName: 'Motion to Dismiss Appeal',
    category: 'appellate',
    shortDoc: 'Asks an appellate court to dismiss the appeal, typically for want of jurisdiction or mootness.',
    source: 'practice',
  },
  {
    slug: 'dismissForLackOfJurisdiction',
    displayName: 'Motion to Dismiss for Lack of Jurisdiction',
    category: 'disposition',
    shortDoc: 'Asks the court to dismiss because it lacks subject-matter or personal jurisdiction.',
    source: 'frcp',
    aliases: ['12(b)(1)', '12(b)(2)'],
  },
  {
    slug: 'disqualify',
    displayName: 'Motion to Disqualify',
    category: 'procedural',
    shortDoc: 'Asks the court to remove a judge or attorney from the case (generic).',
    source: 'user-data',
    aliases: ['DQ', 'Disqualification'],
  },
  {
    slug: 'disqualifyCounsel',
    displayName: 'Motion to Disqualify Counsel',
    category: 'procedural',
    shortDoc: 'Asks the court to remove opposing counsel due to a conflict of interest or ethical bar.',
    source: 'practice',
    aliases: ['DQ Counsel', 'Conflict of Interest'],
  },
  {
    slug: 'disqualifyExpert',
    displayName: 'Motion to Disqualify Expert',
    category: 'evidence',
    shortDoc: 'Asks the court to bar an opposing expert, often under Daubert or for prior consultation.',
    source: 'practice',
    aliases: ['Daubert Expert', 'Expert DQ'],
  },
  {
    slug: 'disqualifyJudge',
    displayName: 'Motion to Disqualify Judge',
    category: 'procedural',
    shortDoc: 'Asks to remove the assigned judge based on constitutional or statutory grounds.',
    source: 'practice',
    aliases: ['Judicial DQ'],
  },
  {
    slug: 'disqualifyJuror',
    displayName: 'Motion to Disqualify Juror',
    category: 'procedural',
    shortDoc: 'Asks the court to strike a prospective juror for cause during voir dire.',
    source: 'practice',
    aliases: ['Challenge for Cause'],
  },
  {
    slug: 'enterOrder',
    displayName: 'Motion to Enter Order',
    category: 'family-law',
    shortDoc: 'Asks the court to sign a proposed order after the parties have reached an agreement.',
    source: 'practice',
    aliases: ['Enter Order'],
  },
  {
    slug: 'exclude',
    displayName: 'Motion to Exclude',
    category: 'evidence',
    shortDoc: 'Asks the court to exclude specific evidence or expert testimony.',
    source: 'practice',
    aliases: ['Daubert'],
  },
  {
    slug: 'expungeLisPendens',
    displayName: 'Motion to Expunge Lis Pendens',
    category: 'procedural',
    shortDoc: 'Asks the court to remove a recorded notice of pending litigation against real property.',
    source: 'user-data',
    aliases: ['Lis Pendens'],
  },
  {
    slug: 'intervene',
    displayName: 'Motion to Intervene',
    category: 'procedural',
    shortDoc: 'Asks the court to allow a non-party to join the case as an intervenor.',
    source: 'frcp',
    aliases: ['Rule 24', 'Intervention'],
  },
  {
    slug: 'joinder',
    displayName: 'Motion to Join Party',
    category: 'procedural',
    shortDoc: 'Asks the court to add an additional party as plaintiff or defendant.',
    source: 'frcp',
    aliases: ['Joinder', 'Rule 19', 'Rule 20'],
  },
  {
    slug: 'modifyChildSupport',
    displayName: 'Motion to Modify Child Support',
    category: 'family-law',
    shortDoc: 'Asks the court to increase or decrease an existing child-support obligation.',
    source: 'practice',
    aliases: ['Modify Support'],
  },
  {
    slug: 'modifyConservatorship',
    displayName: 'Motion to Modify Conservatorship',
    category: 'family-law',
    shortDoc: 'Asks the court to change custody or conservatorship of a child.',
    source: 'practice',
    aliases: ['Custody Modification'],
  },
  {
    slug: 'modifyVisitation',
    displayName: 'Motion to Modify Visitation',
    category: 'family-law',
    shortDoc: 'Asks the court to change the schedule or terms of a parent’s periods of possession.',
    source: 'practice',
    aliases: ['Modify Possession'],
  },
  {
    slug: 'quashIndictment',
    displayName: 'Motion to Quash Indictment',
    category: 'other',
    shortDoc: 'Asks a criminal court to invalidate a defective indictment or information.',
    source: 'practice',
    aliases: ['Quash Indictment'],
  },
  {
    slug: 'quashSubpoena',
    displayName: 'Motion to Quash Subpoena',
    category: 'discovery',
    shortDoc: 'Asks the court to invalidate a subpoena.',
    source: 'practice',
    aliases: ['Quash'],
  },
  {
    slug: 'recuse',
    displayName: 'Motion to Recuse',
    category: 'procedural',
    shortDoc: 'Asks a judge to step aside due to bias or conflict of interest.',
    source: 'texas-rules',
    aliases: ['Recusal'],
  },
  {
    slug: 'reinstateAppeal',
    displayName: 'Motion to Reinstate Appeal',
    category: 'appellate',
    shortDoc: 'Asks an appellate court to reinstate an appeal that was previously dismissed.',
    source: 'practice',
  },
  {
    slug: 'reopenImmigration',
    displayName: 'Motion to Reopen (Immigration)',
    category: 'other',
    shortDoc: 'Asks the BIA or immigration court to reopen proceedings based on new facts or evidence.',
    source: 'practice',
    aliases: ['BIA Reopen'],
  },
  {
    slug: 'resetHearing',
    displayName: 'Motion to Reset Hearing',
    category: 'scheduling',
    shortDoc: 'Asks the court to reschedule a previously set hearing.',
    source: 'practice',
    aliases: ['Reset'],
  },
  {
    slug: 'setAsideDecree',
    displayName: 'Motion to Set Aside Decree',
    category: 'family-law',
    shortDoc: 'Asks the court to vacate a final divorce decree, often paired with a bill of review.',
    source: 'user-data',
    aliases: ['Set Aside', 'Vacate Decree'],
  },
  {
    slug: 'setAsideDefault',
    displayName: 'Motion to Set Aside Default',
    category: 'procedural',
    shortDoc: 'Asks the court to vacate a default judgment so the case can be defended.',
    source: 'practice',
  },
  {
    slug: 'severClaims',
    displayName: 'Motion to Sever Claims',
    category: 'procedural',
    shortDoc: 'Asks the court to separate claims into distinct actions under Rule 21 / TRCP 41.',
    source: 'practice',
    aliases: ['Sever Claims'],
  },
  {
    slug: 'strike',
    displayName: 'Motion to Strike',
    category: 'procedural',
    shortDoc: 'Asks the court to remove a pleading, affidavit, or evidence from the record.',
    source: 'user-data',
  },
  {
    slug: 'strikeAffidavit',
    displayName: 'Motion to Strike Affidavit',
    category: 'evidence',
    shortDoc: 'Asks the court to strike an affidavit as defective, hearsay, or sham.',
    source: 'practice',
  },
  {
    slug: 'strikeBrief',
    displayName: 'Motion to Strike Brief',
    category: 'appellate',
    shortDoc: 'Asks the appellate court to strike a brief for noncompliance with appellate rules.',
    source: 'practice',
  },
  {
    slug: 'strikePleadings',
    displayName: 'Motion to Strike Pleadings',
    category: 'procedural',
    shortDoc: 'Asks the court to strike a pleading (e.g., for sham, scandal, or as a discovery sanction).',
    source: 'practice',
  },
  {
    slug: 'strikeTestimony',
    displayName: 'Motion to Strike Testimony',
    category: 'evidence',
    shortDoc: 'Asks the court to strike trial testimony from the record and instruct the jury to disregard.',
    source: 'practice',
  },
  {
    slug: 'substituteCounsel',
    displayName: 'Motion to Substitute Counsel',
    category: 'procedural',
    shortDoc: 'Notifies the court that one attorney is replacing another for a party.',
    source: 'user-data',
    aliases: ['Substitution of Counsel'],
  },
  {
    slug: 'supplementTheRecord',
    displayName: 'Motion to Supplement the Record',
    category: 'appellate',
    shortDoc: 'Asks the appellate court to add items to the appellate record.',
    source: 'texas-rules',
    aliases: ['Supplement Record'],
  },
  {
    slug: 'suppress',
    displayName: 'Motion to Suppress',
    category: 'evidence',
    shortDoc: 'Asks a criminal court to exclude evidence obtained in violation of constitutional rights.',
    source: 'practice',
    aliases: ['Suppress Evidence', '4th Amendment'],
  },
  {
    slug: 'suspendEnforcement',
    displayName: 'Motion to Suspend Enforcement',
    category: 'appellate',
    shortDoc: 'Asks the court to suspend enforcement of a money judgment pending review.',
    source: 'user-data',
    aliases: ['Supersedeas'],
  },
  {
    slug: 'transferVenue',
    displayName: 'Motion to Transfer Venue',
    category: 'procedural',
    shortDoc: 'Asks the court to move the case to a different county or district.',
    source: 'practice',
    aliases: ['Change of Venue', 'Venue'],
  },
  {
    slug: 'withdrawCounsel',
    displayName: 'Motion to Withdraw',
    category: 'procedural',
    shortDoc: 'Attorney asks the court for permission to stop representing a party.',
    source: 'user-data',
    aliases: ['Withdrawal of Counsel', 'Withdraw'],
  },
  {
    slug: 'other',
    displayName: 'Other Motion',
    category: 'other',
    shortDoc: 'Catch-all for motion types not in this catalog (UI shows a free-text fallback).',
    source: 'practice',
  },
  {
    slug: 'modifyParentChildRelationship',
    displayName: 'Petition / Motion to Modify Parent-Child Relationship',
    category: 'family-law',
    shortDoc: 'Asks the court to modify a prior SAPCR order (Texas).',
    source: 'user-data',
    aliases: ['SAPCR', 'Modify SAPCR'],
  },
  {
    slug: 'rule91aDismiss',
    displayName: 'Rule 91a Motion to Dismiss',
    category: 'disposition',
    shortDoc: 'Texas-specific motion to dismiss baseless causes of action under TRCP 91a.',
    source: 'user-data',
    aliases: ['91a', 'Rule 91a'],
  },
];
